name: ai_accountant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  file_picker: ^6.1.1
  google_generative_ai: ^0.3.2
  syncfusion_flutter_pdf: ^24.2.3
  json_annotation: ^4.8.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
